- name: Install Docker and deploy application
  hosts: all
  become: yes
  vars:
    CTOP_VERSION: "0.7.3"
    DOCKER_PACKAGES:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install packages needed for Docker
      apt:
        name: "{{ DOCKER_PACKAGES }}"
        state: present
        force_apt_get: "yes"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Save the current Ubuntu release version into a variable
      shell: lsb_release -cs
      register: ubuntu_version

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install Docker
      apt:
        name: "docker-ce"
        state: present
        force_apt_get: "yes"

    - name: Test Docker with hello world example
      shell: "docker run hello-world"
      register: hello_world_output

    - name: Show output of hello world example
      debug:
        msg: "Container Output: {{ hello_world_output.stdout }}"

    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user {{ ansible_user }} to docker group
      user:
        name: "{{ ansible_user }}"
        groups: "docker"
        append: "yes"

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'

    - name: Copy Docker Compose file to target VM
      copy:
        src: /ansible/docker-compose.yml
        dest: docker-compose.yml

    - name: Copy environment file to target VM
      copy:
        src: /ansible/.env
        dest: .env

    - name: Start Docker Compose application
      command: docker-compose -f docker-compose.yml up -d
